[tools]
node = "lts"
neovim = "latest"
fzf = "latest"
zoxide = "latest"
eza = "latest"
zellij = "latest"
fd = "latest"
ripgrep = "latest"
bat = "latest"
lazygit = "latest"
starship = "latest"
gemini-cli = "latest"

[settings]
activate_aggressive = true

